const GET_ALL_QUESTIONS= `question:GET_ALL_QUESTIONS`;
const DELETE_QUESTIONS = `question:DELETE_QUESTIONS`;
const UPDATE_QUESTIONS = `question:UPDATE_QUESTIONS`;
const ADD_NEW_QUESTIONS = `question:ADD_NEW_QUESTIONS`;

module.exports = {
  GET_ALL_QUESTIONS,
  DELETE_QUESTIONS,
  UPDATE_QUESTIONS,
  ADD_NEW_QUESTIONS,
};
