const GET_ALL_ANSWERS= `answer:GET_ALL_ANSWERS`;
const DELETE_ANSWERS = `answer:DELETE_ANSWERS`;
const UPDATE_ANSWERS = `answer:UPDATE_ANSWERS`;
const ADD_NEW_ANSWERS = `answer:ADD_NEW_ANSWERS`;

module.exports = {
  GET_ALL_ANSWERS,
  DELETE_ANSWERS,
  UPDATE_ANSWERS,
  ADD_NEW_ANSWERS,
};
